---
- name: Upgrade website
  hosts: tag_webservers
  serial: 1
  gather_facts: true
  vars:
    - message: "Welcome to our new website!"
  tasks:
  - name: Setup provider
    set_fact:
     provider:
       server: "10.10.21.200"
       user: "admin"
       password: "admin"
       server_port: "8443"
       validate_certs: "no"
    delegate_to: localhost

  - name: Remove this webserver from loadbalancer
    bigip_pool_member:
      provider: "{{provider}}"
      state: "disabled"
      host: "{{ ansible_host }}"
      port: 80
      pool: "http_pool"
    delegate_to: localhost

  - name: Wait 5 seconds to show this server is now disabled
    pause:
      seconds: 5

  - name: stop service
    service:
      name: httpd
      state: stopped
    become: true

  - name: copy new template
    template:
      src: index_new.html.j2
      dest: /var/www/html/index.html
    become: true
    
  - name: start service
    service:
      name: httpd
      state: started
    become: true
    
  - name: Add this webserver again to loadbalancer
    bigip_pool_member:
      provider: "{{provider}}"
      state: "enabled"
      host: "{{ ansible_host }}"
      port: 80
      pool: "http_pool"
    delegate_to: localhost
